---
- name: Update installed packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Install base packages
  ansible.builtin.dnf:
    name:
      - git
      - unzip
      - tar
      - gzip
      - jq
      - wget
    state: present